#!bin/bash

# Import CSVs with subject, object, and predicate information into Neo4j database
# Assumes this file is run in the Neo4j directory and the CSV are in this directory
# This import has arrays delimited by '`' because other characters (including ',' and ';') were
# already used in the CSV files.  The array delimiters can be changed manually by starting Neo4j
# and using the commands "match ()-[r:TYPE]-() set r.pmid = replace(r.pmid,'`',',')" for relationships
# and "match (s) set s.type = replace(s.type,'`',',')" for nodes.
bin/neo4j-import --into data/graph.db --nodes:PHRASE 'phrase_label.csv','words4' --relationships 'sub_to_obj.csv','preds2' --delimiter 'TAB' --array-delimiter '`'
